/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appthoitiet;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */

public class FromDangNhap extends javax.swing.JFrame {
    User thisUser = new User();
    /**
     * Creates new form TestGiaoDien
     */
    public FromDangNhap() {
        initComponents();
        //this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_FormLogin = new javax.swing.JLabel();
        jLabel1_Close = new javax.swing.JLabel();
        jLabel1_Min = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel2_Username = new javax.swing.JLabel();
        jTextField1_Username = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1_Login = new javax.swing.JButton();
        jLabel3_Password = new javax.swing.JLabel();
        jButton2_Reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(217, 30, 24));

        jLabel1_FormLogin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1_FormLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_FormLogin.setText("FORM LOGIN");

        jLabel1_Close.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1_Close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Close.setText("X");
        jLabel1_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_CloseMouseClicked(evt);
            }
        });

        jLabel1_Min.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1_Min.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Min.setText("-");
        jLabel1_Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_MinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1_FormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_Min, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_Min, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_FormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));

        jLabel2_Username.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2_Username.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2_Username.setText("Username");

        jTextField1_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_UsernameActionPerformed(evt);
            }
        });

        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });

        jButton1_Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_Login.setText("Login");
        jButton1_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LoginActionPerformed(evt);
            }
        });

        jLabel3_Password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3_Password.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3_Password.setText("Password");

        jButton2_Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2_Reset.setText("Reset");
        jButton2_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ResetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Đăng nhập với tư cách khách");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2_Username)
                    .addComponent(jLabel3_Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1_Login)
                .addGap(85, 85, 85)
                .addComponent(jButton2_Reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_Username)
                    .addComponent(jTextField1_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Login)
                    .addComponent(jButton2_Reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_UsernameActionPerformed

    private void jButton1_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LoginActionPerformed
        // Thông báo nếu Username trống:
        if(jTextField1_Username.getText().equals("")){
            JOptionPane.showMessageDialog(this , "Vui lòng điền Username");
        }else if(jPasswordField2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền Password");
        }else{
          boolean tonTai;
            try {
                tonTai = kiemTra();
                 if(tonTai == true){                
                    FromGiaoDien dd = new FromGiaoDien(thisUser);
                    dd.setVisible(true); 
                    dd.setVisible(true);  
                    dd.pack();
                    dd.setLocationRelativeTo(null);
                    dd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    this.dispose();
                }else{
                JOptionPane.showMessageDialog(this, "Sai tài khoản/mật khẩu");
                }
            } catch (IOException ex) {
                Logger.getLogger(FromDangNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1_LoginActionPerformed


    public class User_login {
        final public  String ID;
        final public  String PW;
        User_login(String Identify, String Password){
             ID=Identify;
             PW=Password;  
        }
        User_login(){
            ID="";
            PW="";  
        }
        public URL get_URL() throws MalformedURLException{
            String link="https://doandieukhien.000webhostapp.com/user.php?field=login";
            link=link+"&id="+ID+"&pw="+PW;
            URL url=new URL(link);
            return url; }
        public void show_URL() throws MalformedURLException{
            URL url;
            url=get_URL();
            System.out.println(url.toString());} 
    }

   
        public boolean kiemTra () throws MalformedURLException, IOException  {
            User_login us=new User_login(jTextField1_Username.getText(),String.valueOf(jPasswordField2.getPassword())); 
            us.show_URL();
            
           // URL url = new URL("https://doandieukhien.000webhostapp.com/welcome/signin.php?id=vophuocnguyen&pw=vophuocnguyen");
            //RL url2 = new URL(us.get_URL().toString()); // Đối tượng us có phương thức get_URL mà lớp URL lại có getString.
            try (BufferedReader br = new BufferedReader(new InputStreamReader(us.get_URL().openStream()))) {
                
                String line;

                String sb = new String();

                while ((line = br.readLine()) != null) {

                    sb=sb+line;                //sb=sb+System.lineSeparator();
                }
                System.out.println(sb);
                System.out.println(sb.startsWith("1")); //sử dụng .startsWith của String để kiểm tra đăng nhập.
                if(sb.startsWith("0") || sb.startsWith("1"))
                {
                    if(sb.startsWith("0")){
                        thisUser.Ad=false;
                    }
                    else {
                        thisUser.Ad=true;
                    }
                    thisUser.ID=us.ID;
                    thisUser.PW=us.PW;
                    thisUser.NAME=sb.substring(1,sb.length());
                    //thisUser.Ad=sb[0];
                    //thisUser.FN=sb-sb[0];
                    return true;
                }   
            
        } catch (IOException ex) {
            Logger.getLogger(FromDangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }    
        return false;
  }


    private void jButton2_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ResetActionPerformed
        // TODO add your handling code here:
        jTextField1_Username.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_jButton2_ResetActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        FromKhach fk = new FromKhach();
       // JDialog jd = new JDialog(fk.setVisible(), true); 
         fk.setVisible(true);  
         fk.pack();
         fk.setLocationRelativeTo(null);
         fk.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1_CloseMouseClicked

    private void jLabel1_MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_MinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel1_MinMouseClicked

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        jButton1_Login.doClick();
    }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1_Login;
    private javax.swing.JButton jButton2_Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Close;
    private javax.swing.JLabel jLabel1_FormLogin;
    private javax.swing.JLabel jLabel1_Min;
    private javax.swing.JLabel jLabel2_Username;
    private javax.swing.JLabel jLabel3_Password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1_Username;
    // End of variables declaration//GEN-END:variables
}
